"""05-02-r1-back-to-direct-rel

Revision ID: 2709a134b8ec
Revises: d1c27e320257
Create Date: 2024-02-05 13:43:28.060635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2709a134b8ec'
down_revision: Union[str, None] = 'd1c27e320257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user-post-relations_post_id', table_name='user-post-relations')
    op.drop_index('ix_user-post-relations_user_id', table_name='user-post-relations')
    op.add_column('posts', sa.Column('owner', sa.Integer(), nullable=True))
    op.drop_index('ix_posts_relation', table_name='posts')
    op.create_index(op.f('ix_posts_owner'), 'posts', ['owner'], unique=False)
    op.drop_constraint('posts_relation_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['owner'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'relation')
    op.add_column('users', sa.Column('posts', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True))
    op.create_index(op.f('ix_users_posts'), 'users', ['posts'], unique=False)
    op.drop_table('user-post-relations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_posts'), table_name='users')
    op.drop_column('users', 'posts')
    op.add_column('posts', sa.Column('relation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_relation_fkey', 'posts', 'user-post-relations', ['relation'], ['post_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_owner'), table_name='posts')
    op.create_index('ix_posts_relation', 'posts', ['relation'], unique=False)
    op.drop_column('posts', 'owner')
    op.create_table('user-post-relations',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='user-post-relations_post_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user-post-relations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', name='user-post-relations_pkey')
    )
    op.create_index('ix_user-post-relations_user_id', 'user-post-relations', ['user_id'], unique=False)
    op.create_index('ix_user-post-relations_post_id', 'user-post-relations', ['post_id'], unique=False)
    # ### end Alembic commands ###
