"""14-04-remove-child-amounts

Revision ID: 4d1cba616be8
Revises: fda9a88df550
Create Date: 2024-04-14 14:06:41.824615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1cba616be8'
down_revision: Union[str, None] = 'fda9a88df550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_children_comment_amount', table_name='comments')
    op.drop_column('comments', 'children_comment_amount')
    op.drop_index('ix_posts_comment_amount', table_name='posts')
    op.drop_column('posts', 'comment_amount')
    op.drop_index('ix_users_comment_amount', table_name='users')
    op.drop_column('users', 'comment_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index('ix_users_comment_amount', 'users', ['comment_amount'], unique=False)
    op.add_column('posts', sa.Column('comment_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index('ix_posts_comment_amount', 'posts', ['comment_amount'], unique=False)
    op.add_column('comments', sa.Column('children_comment_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index('ix_comments_children_comment_amount', 'comments', ['children_comment_amount'], unique=False)
    # ### end Alembic commands ###
