"""08-04-add-parent-comment

Revision ID: 839754d507ce
Revises: b471267e64ab
Create Date: 2024-04-08 21:30:53.089061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839754d507ce'
down_revision: Union[str, None] = 'b471267e64ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comments_parent_comment'), 'comments', ['parent_comment'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'comment_amount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'comment_amount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'comment_amount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'comment_amount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_comment'), table_name='comments')
    op.drop_column('comments', 'parent_comment')
    # ### end Alembic commands ###
