"""02_02_rev2_rm_post_owner

Revision ID: bd3d5c5c9ff4
Revises: c2748ba51819
Create Date: 2024-02-02 10:52:01.228543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3d5c5c9ff4'
down_revision: Union[str, None] = 'c2748ba51819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_owner', table_name='posts')
    op.drop_constraint('posts_owner_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_owner_fkey', 'posts', 'user-post-relations', ['owner'], ['post_id'], ondelete='CASCADE')
    op.create_index('ix_posts_owner', 'posts', ['owner'], unique=False)
    # ### end Alembic commands ###
