"""02_02_rev3_add_rel_to_post

Revision ID: d1c27e320257
Revises: bd3d5c5c9ff4
Create Date: 2024-02-02 10:59:38.400671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c27e320257'
down_revision: Union[str, None] = 'bd3d5c5c9ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('relation', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_relation'), 'posts', ['relation'], unique=False)
    op.create_foreign_key(None, 'posts', 'user-post-relations', ['relation'], ['post_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_relation'), table_name='posts')
    op.drop_column('posts', 'relation')
    # ### end Alembic commands ###
