"""11-04-children-comment-amount

Revision ID: fda9a88df550
Revises: 839754d507ce
Create Date: 2024-04-11 17:42:55.191637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda9a88df550'
down_revision: Union[str, None] = '839754d507ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('children_comment_amount', sa.Integer(), nullable=True, server_default='0'))
    op.create_index(op.f('ix_comments_children_comment_amount'), 'comments', ['children_comment_amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_children_comment_amount'), table_name='comments')
    op.drop_column('comments', 'children_comment_amount')
    # ### end Alembic commands ###
